"""
Django settings for gpt_pjt project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
# 💡 .env 파일에 있는 django 시크릿 키 사용하기
import os
from dotenv import load_dotenv

# 💡.env 파일 로드
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# 💡 환경변수에서 SECRET_KEY 가져오기 (없으면 오류 발생 방지)
SECRET_KEY = os.getenv("SECRET_KEY")

# 💡 SECRET_KEY가 없을 경우 예외 처리 (보안상 필수)
if not SECRET_KEY:
    raise ValueError("SECRET_KEY가 설정되지 않았습니다! .env 파일을 확인하세요.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    "django_seed",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    # shell_plus 여기 들어있음
    "django_extensions",
    # 사용자 정의 앱
    "accounts",
    "chat",
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gpt_pjt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gpt_pjt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# 커스텀 유저 모델 설정
AUTH_USER_MODEL = 'accounts.User'

# JWT 설정
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
}

# JWT 유효기간 설정 
SIMPLE_JWT = {
    # 요청할 때마다 인증을 위해 헤더에 포함해야 하는 토큰
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=1440),
    # 엑세스 토큰이 만료되었을 때, 새로 엑세스 토큰을 발급받기 위한 토큰
    # 만일 리프레시 토큰까지 만료되었다면 다시 인증(로그인)과정이 필요함
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    
    # 로테이션 리프레시 토큰을 True로 하면 새로운 리프레시 토큰을 줄 때, 새로운 액세스 토큰이랑 같이 준다.
    "ROTATE_REFRESH_TOKENS": True,
    
    # 리프레시 토큰이 회전 후 블랙리스트에 자동으로 추가되도록 설정
    # 새로운 리프레시를 줬으면, 이전 리프레시는 이제 유효하지 않아야 하니 그것을 블랙리스트로 넣겠다는 설정.
    # 즉 불랙리스트를 DB에 저장해줘야겠지 (이제 예전 리프레시는 다시 던져도 동작하지 않음!)
    # 즉, 테이블이 필요하니 이 설정 후 migrate 해줘야 한다.
    "BLACKLIST_AFTER_ROTATION": True,
    
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
