# Generated by Django 4.2 on 2025-01-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="genre",
            field=models.CharField(default="기타", max_length=50),
        ),
    ]
