# Generated by Django 4.2 on 2025-01-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_article_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="genre",
        ),
    ]
