# Generated by Django 4.2 on 2025-01-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_remove_article_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
